module.exports.de = "Die Regeln:" + "\n";
module.exports.de += "\n";
module.exports.de += "1) Benehmt Euch!" + "\n";
module.exports.de += "==>Verhaltet Euch so als könnte der andere Euch jederzeit eine Ohrfeige geben wenn Ihr Euch danebenbenehmt." + "\n";
module.exports.de += "\n";
module.exports.de += "2) Schreibt keine vertraulichen Daten im Chat, egal wo!" + "\n";
module.exports.de += "==>Stellt euch vor ihr schreibt alles auf Postkarten. Vermutlich liest es eh keiner, aber wer garantierts?" + "\n";
module.exports.de += "\n";
module.exports.de += "3) Das ist ein privater Server, es gibt kein 'Recht' hier zu sein." + "\n";
module.exports.de += "==>Willkommen ist jeder der sich benehmen kann." + "\n";

module.exports.en = "The rules:\n";
module.exports.en += "" + "\n";
module.exports.en += "1) Behave!" + "\n";
module.exports.en += "==>Behave as if the person on the other end could slap you any time you cross a line." + "\n";
module.exports.en += "\n" + "\n";
module.exports.en += "2) Don't write anything private in the chat, no matter where!" + "\n";
module.exports.en += "==>Imagine every posting is a post card. Probably no one is interested anyway, but how can you be certain?" + "\n";
module.exports.en += "\n" + "\n";
module.exports.en += "3) This is a private server, there is no 'right' to be here." + "\n";
module.exports.en += "==>Everyone is welcome as long as they behave." + "\n";

module.exports.tlh = "yIpab:\n";
module.exports.tlh += "1) romuluSngan yIDaQo!\n";
module.exports.tlh += "==>Hoch nIqIplaH yIghet. yIQaqQo'\n";
module.exports.tlh += "\n";
module.exports.tlh += "2) pagh pegh yIghItlh! paghDaq!\n";
module.exports.tlh += "==>Se' So'be'. ghaytan pagh Qoy'lu', 'ach DaSuDnIS?\n";
module.exports.tlh += "\n";
module.exports.tlh += "3) Se'vam maSeH, machaw'mo' naDev SoHtaH.\n";
module.exports.tlh += "==>yISengmoHbe', bIratlhlaHtaH.\n";
